### ISSUE TITLE
Panagram view . failed due to unknown sample 'aethiopicum3'

### ISSUE THREAD

**Issue by roylejw** [kjenike/Panagram#14]
Hi all,

Running into an error when trying to view both the test dataset and my own dataset. Indexing works fine, but when running 
`panagram view .` 

I encounter the following error:
`Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/panagram", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/panagram/__main__.py", line 122, in main
    args.main.run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/panagram/__main__.py", line 107, in run
    return self.cmd.run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/panagram/__main__.py", line 60, in run
    view(self)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/panagram/view.py", line 1171, in view
    for i in range(1, num_chrs[anchor_name]+1):
KeyError: 'aethiopicum3'
`

Looking in view.py, it seems like this anchor name is hard-coded? When changing this to ecoli to match an anchor in the example dataset, I get past this error, but then run into a second error where it tries to find the annotation_tab_file called "gene_vars.txt", also hardcoded in view.py (but not generated at the index stage?):

`Quering genes 4
Queried genes 4
Quering genes 5
Queried genes 5
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/panagram", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/panagram/__main__.py", line 122, in main
    args.main.run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/panagram/__main__.py", line 107, in run
    return self.cmd.run()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/panagram/__main__.py", line 60, in run
    view(self)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/panagram/view.py", line 1270, in view
    annotation_tab_df = annotation_tab_info(annotation_tab_file)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/panagram/view.py", line 71, in annotation_tab_info
    with open(file_name, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'gene_vars.txt'`

Anyone have any ideas as to how to get past these two errors? Or if I'm missing something obvious?

**Comment by qiwang7** [comment]
Have the same problem. Seems to have solved the issue by downloading the dev branch:
git clone -b dev --recursive https://github.com/kjenike/panagram.git

The the error will be "KeyError: 'kakapo'", but it can be solved the same way as you solved the "KeyError: 'aethiopicum3'" issue. (mentioned in one of the previous issue)

**Comment by roylejw** [comment]
Legend, thank you! That worked!

**Comment by nlbrown62** [comment]
This should be fixed in the latest version!
