### ISSUE TITLE
can't adjust k-mer size

### ISSUE THREAD

**Issue by laramiemckenna** [kjenike/Panagram#15]
Hey there! 

First of all, I'm so excited about panagram. :) I know that it will really illuminate a lot in the system I'm studying. After some troubleshooting, I got it working on both the test data and my own data without changing any of the parameters in conf.toml file.

However, I've run into an issue where I cannot change the k-mer size to anything other than 12. Even if I removed the k = 12 and allow it to run in default mode (for k = 21), I get the same error as shown below. I was able to change other hardcoded processes, like thread count, but I do not know how to resolve this one. In the past, when I've gotten this error, it has been due to a conflict between the conf.toml file and a hardcoded parameter, but that no longer appears to be the case. It runs smoothly as soon as I set k to 12 again.

Any thoughts as to what might be going on or how I can temporarily change the k-mer size? 

```
(panagram) laramieakozbek@laramies-mbp sample_data % panagram index conf.toml 
['id', 'size']
                 id       size
genome    chr                 
sample_1  chr01   1   63013536
          chr02   1  102123159
          chr03   1   82480234
          chr04   1  105958959
          chr05   1   99482745
...              ..        ...
sample_2 Chr08   8   75550986
          Chr09   8   70775745
          Chr10   8   65277395
          Chr11   8   64529631
          Chr12   8   44989153

[99 rows x 2 columns]
************************
Error: Error: Cannot open temporary file ./tmp/q_glauca/kmc_00253.bin
Traceback (most recent call last):
  File "/Users/laramieakozbek/miniforge3/envs/panagram/bin/panagram", line 8, in <module>
    sys.exit(main())
  File "/Users/laramieakozbek/miniforge3/envs/panagram/lib/python3.7/site-packages/panagram/__main__.py", line 122, in main
    args.main.run()
  File "/Users/laramieakozbek/miniforge3/envs/panagram/lib/python3.7/site-packages/panagram/__main__.py", line 107, in run
    return self.cmd.run()
  File "/Users/laramieakozbek/miniforge3/envs/panagram/lib/python3.7/site-packages/panagram/index.py", line 112, in run
    self.write()#args)
  File "/Users/laramieakozbek/miniforge3/envs/panagram/lib/python3.7/site-packages/panagram/index.py", line 345, in write
    bitvec_dbs = self._run_kmc()
  File "/Users/laramieakozbek/miniforge3/envs/panagram/lib/python3.7/site-packages/panagram/index.py", line 654, in _run_kmc
    i,name,db = self._run_kmc_genome(args)
  File "/Users/laramieakozbek/miniforge3/envs/panagram/lib/python3.7/site-packages/panagram/index.py", line 609, in _run_kmc_genome
    subprocess.check_call(cmd)
  File "/Users/laramieakozbek/miniforge3/envs/panagram/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/laramieakozbek/miniforge3/envs/panagram/lib/python3.7/site-packages/panagram/extra/kmc', '-k21', '-t8', '-m10', '-ci1', '-cs10000000', '-fm', 'fasta/sample_1_genome.fa', './kmc_count/sample_1', './tmp/sample_1']' returned non-zero exit status 1.
```

**Comment by nlbrown62** [comment]
Should be fixed in the latest version on main! Please try that one and reopen if you have any other issues/questions.
