### ISSUE TITLE
Working with larger genomes

### ISSUE THREAD

**Issue by SwansaSwimming** [kjenike/Panagram#7]
Thanks for developing this piece of software. I have managed to install and run Panagram with the example dataset and an Arabidopsis dataset - so far without problems.

However when I moved across to a wheat dataset I encountered this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/panagram", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/panagram/__main__.py", line 122, in main
    args.main.run()
  File "/usr/local/lib/python3.9/site-packages/panagram/__main__.py", line 107, in run
    return self.cmd.run()
  File "/usr/local/lib/python3.9/site-packages/panagram/index.py", line 106, in run
    self.write()#args)
  File "/usr/local/lib/python3.9/site-packages/panagram/index.py", line 355, in write
    self._load_gffs(g)
  File "/usr/local/lib/python3.9/site-packages/panagram/index.py", line 436, in _load_gffs
    self._write_tabix(annos, genome, "anno")
  File "/usr/local/lib/python3.9/site-packages/panagram/index.py", line 414, in _write_tabix
    pysam.tabix_index(tbx, True, 0,1,2)
  File "pysam/libctabix.pyx", line 1027, in pysam.libctabix.tabix_index
OSError: building of index for ./anno/JAG6D.anno.bed.bgz failed
```

After some exploring I have managed to reproduce the error, and it appears to be a consequence of tabix attempting to index the larger wheat chromosomes and failing at the 512Mb point. Is it possible to amend the code to create CSI indices instead, so larger genomes can be tolerated? That would be great....

**Comment by kjenike** [comment]
Hello! Thank you for using panagram!! And thanks for catching this issue. Yes, we think it is possible and we'll work on fixing it soon. I'll update you (hopefully soon) when it works on larger chromosomes.

**Comment by skovaka** [comment]
I've updated the tabix indexing to use CSI indexes, and fixed a couple other issues related larger pan-genomes. Try re-install and let us know how it works!

**Comment by SwansaSwimming** [comment]
Fantastic, thank you!  I will have another go :)
