### ISSUE TITLE
View stalled - how to use chrom option?

### ISSUE THREAD

**Issue by scorreard** [kjenike/Panagram#8]
Hi team,
Thanks for the tool.

I successfully installed it and ran index and view on the test dataset provided.

Then, I moved into using my own data, a set of 12 turtles.
I successfully ran the index (at least it gave me the expected output files), but the view part stalls. It just write nothing and the interface is not accessible.

Two questions :
1. For the genomes I use, the repeats are masked using repeatmasker, may that cause a problem?
2. I wanted to troubleshoot using the `  chrom               Initial chromosome (optional) (default: None)` option, however, I don't understand how to use it. I get `unrecognized arguments`

This is an example of what I ran 
```
panagram view . --host gphost05 --port 99 'spiny_softshell_turtle_GCA_000385615' 'PJP01000002.1'
usage: panagram [-h] {view,index,bitdump} ...
panagram: error: unrecognized arguments: spiny_softshell_turtle_GCA_000385615 PJP01000002.1
```

If you could give an example of how you use the options, that would be appreciated.

Thanks,
Solenne

**Comment by scorreard** [comment]
Following up, **still an issue**

When I let view run for long enough, I obtain this : 

```
miniconda3/lib/python3.7/site-packages/panagram/view.py:1493: PerformanceWarning: indexing past lexsort depth may impact performance.
  counts = index.chr_bins.loc[(l,c)].sum(axis=0)
```

Please, help me find a solution?

**Comment by kjenike** [comment]
Hello,
I am sorry it took so long to get back to you. I was traveling and just got back today. I will work on finding a solution and get back to you ASAP.

**Comment by skovaka** [comment]
How large are your genomes? I just pushed changes which fixed some errors related to large pan-genomes, so you could try re-installing. Also, I have not experimented much with changing the "host" parameter. You may want to leave it as the default "localhost", and if you're running on a remote server you could access it via SSH port-forwarding (i.e. `ssh -NL 8050:localhost:8050 <user>@<server_address>`)

As for the unrecognized argument issue, you could try putting all of the non-positional arguments first, and not using quotes around the genome and chromosome names (`panagram view --host gphost05 --port 99 . spiny_softshell_turtle_GCA_000385615 PJP01000002.1`). These changes don't make a difference for me, but it could be OS-specific.

**Comment by scorreard** [comment]
Hi Sam,

The genomes are ranging from 1.9Gb to 2.4Gb (12 turtles). Is that too big? Installing panagram was quite an adventure, I would be happy not having to reinstall it.

For the host parameter, it worked fine with your test dataset, so I think it is fine to change it. I don't really have a choice with our server and the VPN / restricted access we have. But I will try your idea too.

Thanks for the new command line, I am trying it right now and it is not throwing an error, this is a good sign. Hopefully it will not get stuck like previously.

**Comment by skovaka** [comment]
Those genomes are not too big, I don't think a reinstall is necessary at this point. Let us know if you have any tips to make installation easier, I know KMC can be difficult on some computers. If you still have problems, could you let me know how many chromosomes are in your genomes? Running `wc -l chrs.csv` in your panagram directory would be a quick way to determine that. If it's a performance issue, my first thought is maybe we need to optimize for more fragmented genomes

**Comment by scorreard** [comment]
Hi Sam,

**Installation feedback :**
I had this error 
```
      error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>
```
which got resolved by adding the following code to setup.py
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

I think pretty much everything else was mostly version compatibility issues within the conda environment. I don't remember exactly.

**Turtle issue**
```
wc -l chrs.csv
592313 chrs.csv
```

Yes, indeed, that may be the issue. Should it only be chromosome-level assemblies?

**Comment by kjenike** [comment]
Ah, I bet Sam is right, the number of scaffolds could be the issue. panagram doesn't necessarily need chromosome scale assemblies, but it would be helpful to have at least one assembly with a limited number of scaffolds. 

Right now, we have an option where "samples" can be raw sequencing reads rather than assemblies. In this way, each read is treated like a scaffold. However, this set-up requires at least one assembly that is close to chromosome scale, or at least has a limited number of scaffolds. The viewing is then anchored on that decent assembly, while the pan-genome k-mers are taken from all of the samples (including samples that are just raw reads). 

I can think of a few possible quick solutions to this problem. If you have one assembly that is better than the rest, then you can use that assembly as your only anchor. This approach would be similar to raw reads approach in the above paragraph. Alternatively, if all your assemblies have a few long scaffolds and many small scaffolds, we could set a scaffold viewing length limit. For example, panagram could render only scaffolds over 10mbp (or something like that). I think the best approach will depend on your assembly characteristics. Do you happen to have an Nchart for your assemblies? Or do you know the N50s?

**Comment by scorreard** [comment]
We do have one assembly that is chromosome scale, I will use that one as an anchor and try again.
I don't need to re-do the indexing right, I just use it as the anchor during the viewing step?

I will be using caretta caretta as the anchor : 28 chromosomes, Scaffold N50 = 131 Mb
https://www.ncbi.nlm.nih.gov/data-hub/taxonomy

**Comment by scorreard** [comment]
Ok, new error, it doesn't recognize the genome as an anchor

```
panagram view . --host gphost05 --port 99 loggerhead_turtle_GCA_023653815
usage: panagram [-h] {view,index,bitdump} ...
panagram: error: unrecognized arguments: loggerhead_turtle_GCA_023653815
```

even though it's one of the genome name:
```
more genome_dist.tsv 
[...]
loggerhead_turtle_GCA_023653815	spiny_softshell_turtle_GCA_000385615	0.153298	0	204/10000
loggerhead_turtle_GCA_023653815	abingdon_island_giant_tortoise_GCA_003597395	0.0919913	0	781/10000
loggerhead_turtle_GCA_023653815	mccords_box_turtle_GCA_003846335	0.0828134	0	963/10000
loggerhead_turtle_GCA_023653815	amboina_box_turtle_GCA_004028625	0.0850391	0	915/10000
loggerhead_turtle_GCA_023653815	pitted_shelled_turtle_GCA_007922185	0.17026	1.16638e-211	142/10000
loggerhead_turtle_GCA_023653815	dermatemys_mawii_GCA_007922305	0.10029	0	648/10000
loggerhead_turtle_GCA_023653815	green_sea_turtle_GCA_015237465	0.0247067	0	4237/10000
loggerhead_turtle_GCA_023653815	common_snapping_turtle_GCA_018859375	0.0764518	0	1116/10000
loggerhead_turtle_GCA_023653815	northwestern_pond_turtle_GCA_022086475	0.0735321	0	1195/10000
loggerhead_turtle_GCA_023653815	southwestern_pond_turtle_GCA_023634205	0.0724788	0	1225/10000
[...]
```

**Comment by scorreard** [comment]
Latest error message (using caretta caretta as anchor)
```
/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py:1493: PerformanceWarning: indexing past lexsort depth may impact performance.
  counts = index.chr_bins.loc[(l,c)].sum(axis=0)
/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py:890: PerformanceWarning:

indexing past lexsort depth may impact performance.

/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py:891: PerformanceWarning:

indexing past lexsort depth may impact performance.

/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py:992: PerformanceWarning:

indexing past lexsort depth may impact performance.

/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py:1005: PerformanceWarning:

indexing past lexsort depth may impact performance.

/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py:1007: PerformanceWarning:

indexing past lexsort depth may impact performance.

/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py:564: RuntimeWarning:

invalid value encountered in long_scalars

Traceback (most recent call last):
  File "/home/scorreard/miniconda3/bin/panagram", line 8, in <module>
    sys.exit(main())
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/__main__.py", line 122, in main
    args.main.run()
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/__main__.py", line 107, in run
    return self.cmd.run()
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/__main__.py", line 60, in run
    view(self)
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py", line 1773, in view
    figure = create_tree( x_start_init,x_stop_init, all_chrs[chrs][int(x_start_init/n_skips_start):int(x_stop_init/n_skips_start)], n_skips_start),
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py", line 418, in create_tree
    y_coords=y_coords)
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py", line 329, in draw_clade
    line_color = palette[int(biggest_num_in_clade(clade, kmer_num))+10]
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py", line 302, in biggest_num_in_clade
    tmp_m = biggest_num_in_clade(c, kmer_num)
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py", line 302, in biggest_num_in_clade
    tmp_m = biggest_num_in_clade(c, kmer_num)
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py", line 302, in biggest_num_in_clade
    tmp_m = biggest_num_in_clade(c, kmer_num)
  [Previous line repeated 6 more times]
  File "/home/scorreard/miniconda3/lib/python3.7/site-packages/panagram/view.py", line 311, in biggest_num_in_clade
    clade_num = kmer_num[tmp_name]
KeyError: 'abingdon_island_giant_tortoise_GCA_00...'
```

**Comment by scorreard** [comment]
Hi team.

Still the same issue, do you know what the "KeyError: 'abingdon_island_giant_tortoise_GCA_00...'" may be?
I'm using a good anchor now.

**Comment by nlbrown62** [comment]
Hello! Please retry with v1.0.0 on main! A lot of old issues were resolved in this version. Feel free to reopen this issue if you encounter any problems.
