### ISSUE TITLE
panagram view . fail. 

### ISSUE THREAD

**Issue by Naibin** [kjenike/Panagram#9]
I have successfully git and  installed panagram.
 then I downloaded example data , panagram index conf.toml   ------------------------this step is ok 

[fsdfdsf example_data]$ panagram view .
Traceback (most recent call last):
  File "/home/naibin/.local/bin/panagram", line 8, in <module>
    sys.exit(main())
  File "/home/naibin/.local/lib/python3.9/site-packages/panagram/__main__.py", line 122, in main
    args.main.run()
  File "/home/naibin/.local/lib/python3.9/site-packages/panagram/__main__.py", line 107, in run
    return self.cmd.run()
  File "/home/naibin/.local/lib/python3.9/site-packages/panagram/__main__.py", line 60, in run
    view(self)
  File "/home/naibin/.local/lib/python3.9/site-packages/panagram/view.py", line 1081, in view
    for i in range(1, num_chrs[anchor_name]+1):
**KeyError: 'kakapo'**
I found a Kakapo-related error, and I installed Kakapo.
-------------------------------------------------------------------------------
[affdsfsfdt example_data]$ kakapo
Kakapo version: 0.9.4
Python version: 3.9.13
Operating system: Fedora 34
System info: 40 physical and 80 logical cores, 472.26 GB RAM (x86_64)

Configuration file was not provided. Nothing to do.

------------------------------------------------------------------------------
usage: kakapo --cfg project_configuration_file --ss search_strategies_file

optional arguments:
  --cfg path           Path to a kakapo project configuration file.
  --ss path            Path to a kakapo search strategies file.
  --ncpu count         Number of CPUs to use.
  --stop-after-filter  Stop kakapo after Kraken2/Bowtie2 filtering step.
  --force-deps         Force the use of kakapo-installed dependencies,
                       even if they are already available on the system.
  --install-deps       Install kakapo dependencies and quit.
  --dnld-kraken-dbs    Download Kraken2 databases and quit.
  --clean-data-dir     Remove cached NCBI taxonomy data and all software
                       dependencies downloaded by kakapo.
  -v, --version        Print kakapo version.
  -h, --help           Print kakapo help information.
------------------------------------------------------------------------------
 kakapo in just an example of a genome.

**Comment by Naibin** [comment]
the next steps will fix this error
1 unzip everything in the "example_data" folder. sometimes it is difficult to unzip bgz files on Linux .
simply download it at https://bx.bio.jhu.edu/data/panagram/example_data.zip on Windows, decompress the package 
, and upload the whole folder to the root of panagram on Linux server.

2 in the example_data directory , run "panagram index conf.toml"


3 ls anchor/
 ecoli.100.bgz
ecoli.100.gzi
ecoli.1.bgz
ecoli.1.gzi
ecoli_K12.100.bgz
ecoli_K12.100.gzi
ecoli_K12.1.bgz
ecoli_K12.1.gzi
klebsiella.100.bgz
klebsiella.100.gzi
klebsiella.1.bgz
klebsiella.1.gzi
salmonella.100.bgz
salmonella.100.gzi
salmonella.1.bgz
salmonella.1.gzi
shigella.100.bgz
shigella.100.gzi
shigella.1.bgz
shigella.1.gzi
You will find a list of genomes.  ecoli, klebsiella,salmonella,shigella is the genome parameter. and there is no "kakabo" !
4  vim /site-packages/panagram/view.py file 
change  kakapo to 'ecoli'
also you can change it to  "lebsiella","salmonella","shigella"
[dsfsdfsdf example_data]$ panagram view .
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'panagram'
 * Debug mode: on 
 it is ok now.

next step for me is to let the service public , and running other than localhost.

**Comment by nlbrown62** [comment]
Should be fixed in the latest version! Please reopen if you find another issue.
